import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';

export default function Layout({ children }) {
  return (<>
    <Head>
      <meta charSet="utf-8" />
      <title>GameVentory</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <Header />
    
    <main 
      className="py-3 bg-light"
      style={{ flex: 1 }}
    >
      { children }
    </main>
    
    <Footer />
  </>)
}