
import Head from 'next/head';
import Link from 'next/link';

// Create a single supabase client for interacting with your database
import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs'
import { useEffect } from 'react';

export default function Home({ games }) {
  return (
    <>
      <Head>
        <title>GameVentory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="container">
        <ul>
          {games.map(game => <li key={game.id}>{game.name}</li>)}
        </ul>
        <Link href="/add-game" className='btn btn-primary'>Add Game</Link>
      </div>
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  // Create authenticated Supabase Client
  const supabase = createServerSupabaseClient(ctx);
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession()
  console.log(session);

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const { data, error } = await supabase
    .from('games')
    .select();

  if(error) {
    // todo: throw error on page
    console.error(error.message);
  }

  return {
    props: {
      games: data,
      initialSession: session,
      user: session.user,
    },
  }
}