
import { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Link from 'next/link';

// Create a single supabase client for interacting with your database
import { createClient } from '@supabase/supabase-js';
import { useSession } from '@supabase/auth-helpers-react';

export default function Home({ data }) {
  const session = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!session) router.push('/login'); 
  }, [session]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="container">
        {session ? (<>
          <ul>
            {data.map(game => <li key={game.id}>{game.name}</li>)}
          </ul>
          <Link href="/add-game" className='btn btn-primary'>Add Game</Link>
        </>) : (
          <p>Redirecting to <Link href="/login">the login page</Link>...</p>
        )}
      </div>
    </>
  )
}

export async function getServerSideProps() {
  // todo: use supabase client from _app?
  const supabase = createClient(process.env.DB_URL, process.env.DB_API_KEY);
  const { data, error } = await supabase
    .from('games')
    .select();

  if(error) {
    // todo: throw error on page
    console.error(error.message);
  }

  return {
    props: { data },
  }
}